spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  cloud:
    gateway:
      mvc:
        routes:
          - id: baidu_route
            uri: https://github.com
            predicates:
              - Path=/baidu/**
            filters:
              - RewritePath=/baidu/?(?<segment>.*), /sunhao1256/${segment}
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-components: always
      show-details: always
  health:
    ping:
      enabled: true
    redis:
      enabled: false
  endpoints:
    web:
      base-path: /metrics
      path-mapping:
         health: ping


